releases:
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 4.7.1
- name: certmanager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: 1.12.0
- name: harbor
  namespace: harbor
  chart: harbor/harbor
  version: 1.12.3
  values:
    - "harbor/values.yaml"
