apiVersion: v1
kind: Pod
metadata:
  name: transit-vault
  namespace: default
  labels:
    app: vault
spec:
  containers:
    - name: transit-vault
      image: hashicorp/vault
      securityContext:
        capabilities:
          add:
            - IPC_LOCK
      env:
        - name: VAULT_ADDR
          value: "http://localhost:8100"
        - name: VAULT_LOCAL_CONFIG
          value: |
            {"storage": {"file": {"path": "/vault/file"}}, "listener": [{"tcp": { "address": "0.0.0.0:8100", "tls_disable": true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}