apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  namespace: {{ .Release.Namespace }}  
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
  - name: tcp-redis
    port: 6379
    targetPort: 6379