apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework # имя CRD должно иметь формат plural.group
spec:
  scope: Namespaced     # Данный CRD будер работать в рамках namespace
  group: otus.homework  # Группа, отражается в поле apiVersion CR
  versions:             # Список версий
    - name: v1
      served: true      # Будет ли обслуживаться API-сервером данная версия
      storage: true     # Фиксирует  версию описания, которая будет сохраняться в etcd
      # subresources describes the subresources for custom resources.
      subresources:
        # status enables the status subresource.
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string # Тип данных поля ApiVersion
            kind:
              type: string # Тип данных поля kind
            metadata:
              type: object # Тип поля metadata
              properties:  # Доступные параметры и их тип данных поля metadata (словарь)
                name:
                  type: string
            spec:
              type: object
              properties:
                image: 
                  type: string
                database:
                  type: string
                password:
                  type: string
                storage_size:
                  type: string
              required: # Указываем обязательные поля для создания CR
                - image
                - database
                - password
                - storage_size
  names:                # различные форматы имени объекта CR
    kind: MySQL         # kind CR (его же укажем в CR.yml)
    plural: mysqls      # Можно увидеть в kubectl api-resources
    singular: mysql
    shortNames:
      - ms
