apiVersion: v1 
kind: Pod 
metadata:
  name: web
  labels: 
    app: nginx
spec:
  containers:
  - name: nginx-yd47
    image: hardkov/yd47_platform:nginx_0.0.1
    volumeMounts:
    - name: workdir
      mountPath: /app
  initContainers:
  - name: install
    image: busybox:1.28
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: workdir
      mountPath: "/app"
  volumes:
  - name: workdir
    emptyDir: {}
